### PR TITLE
Made changes at UI Side

### PR DESCRIPTION
**Pull request by Yagnik-Gohil**
Hello @iamajitsingh I've made changes in html files, hope you like it.

### CODE REVIEW

**Review by iamajitsingh — CHANGES_REQUESTED** [review]
@Yagnik-Gohil 
Nice work! However, few minor issues which I encountered forefront that need fixing:
1. Whenever I select on a created to-do to modify/edit/view it, the buttons 'save', 'delete', 'completed', 'did not complete' aren't visible anymore
2. Due to the footer Signup button is getting blocked on the 'signup' page. Probably it's the same reason for the issue above.
3. Also please make the 'logout' option (when user has logged in) consistent with the sign up and login buttons (all 3 should have the same style)

**Comment by Yagnik-Gohil** [comment]
Hello Ajit, I'va made changes that you want. The issue that you've mentioned (Due to footer things are getting blocked) is not reproducing now. If you want any changes then feel free to ping, Thank you.

**Review by iamajitsingh — CHANGES_REQUESTED** [review]
@Yagnik-Gohil Just check the sign-up page once (When a user tries to create a new account) 

-  Signup Button (At the bottom of the form) is still blocked by footer.

I'd suggest just reduce the width a bit. However, other stuff is working well now as expected.

**Comment by Yagnik-Gohil** [comment]
Hello Ajit, I've reduced size as you've suggested. If it's still not looking good then you should check your browser zoom and set it to 100%. there is bootstrap class in footer --> "fixed-bottom" thats why this Issue is occuring. just remove that If you want.

**Review by iamajitsingh — APPROVED** [review]
Nice Work @Yagnik-Gohil.
Thanks for contributing!

**Pull request merged**
